/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interacao;

import colecao.Colecao;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.ListModel;
import javax.swing.table.DefaultTableModel;
import midia.Musica;

/**
 *
 * @author Leonardo Severo Pedroso
 * <leopedroso45@gmail.com>
 *
 */
public class FormularioMusica extends javax.swing.JFrame {

    private DefaultListModel listaInterpretes;
    private DefaultListModel listaAutores;
    private DefaultTableModel tabela;
    private Colecao colecao;
    private Musica musicaAnterior;

    /**
     * Creates new form FormularioMusica
     */
    public FormularioMusica(Colecao colecao) {
        this.colecao = colecao;
        this.listaAutores = new DefaultListModel();
        this.musicaAnterior = null;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        caminhoI = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tituloI = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        descricaoI = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        idiomaI = new javax.swing.JTextField();
        generoI = new javax.swing.JTextField();
        campoAutor = new javax.swing.JTextField();
        campoInterprete = new javax.swing.JTextField();
        btnAdicionarAutor = new javax.swing.JButton();
        btnAdicionarInterprete = new javax.swing.JButton();
        jScrollPane = new javax.swing.JScrollPane();
        campoAutores = new javax.swing.JList<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        campoInterpretes = new javax.swing.JList<>();
        btnRemoveAutor = new javax.swing.JButton();
        btnRemoveInterprete = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        duracaoI = new javax.swing.JFormattedTextField();
        anoI = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(440, 460));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Insira as informações da Música");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(87, 11, -1, -1));

        jLabel2.setText("Caminho:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 31, -1, -1));
        getContentPane().add(caminhoI, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 51, 158, -1));

        jLabel3.setText("Titulo:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(174, 31, -1, -1));
        getContentPane().add(tituloI, new org.netbeans.lib.awtextra.AbsoluteConstraints(174, 51, 162, -1));

        jLabel4.setText("Descrição:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 77, -1, -1));
        getContentPane().add(descricaoI, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 97, 326, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 128, 346, 10));

        jLabel5.setText("Idioma:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 144, -1, -1));

        jLabel6.setText("Genero:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(174, 144, -1, -1));

        jLabel7.setText("<html><center>Autores:</center></html>");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 253, 160, -1));

        jLabel8.setText("<html><center>Interpretes:</center></html>");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(176, 253, 160, -1));

        jLabel9.setText("Duração:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 202, -1, -1));

        jLabel10.setText("Ano:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(174, 202, -1, -1));
        getContentPane().add(idiomaI, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 164, 160, -1));
        getContentPane().add(generoI, new org.netbeans.lib.awtextra.AbsoluteConstraints(174, 164, 162, -1));
        getContentPane().add(campoAutor, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 273, 160, -1));
        getContentPane().add(campoInterprete, new org.netbeans.lib.awtextra.AbsoluteConstraints(176, 273, 160, -1));

        btnAdicionarAutor.setText("Adicionar");
        btnAdicionarAutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarAutorActionPerformed(evt);
            }
        });
        getContentPane().add(btnAdicionarAutor, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 299, -1, -1));

        btnAdicionarInterprete.setText("Adicionar");
        btnAdicionarInterprete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarInterpreteActionPerformed(evt);
            }
        });
        getContentPane().add(btnAdicionarInterprete, new org.netbeans.lib.awtextra.AbsoluteConstraints(216, 299, -1, -1));

        campoAutores.setMaximumSize(new java.awt.Dimension(420, 0));
        jScrollPane.setViewportView(campoAutores);

        getContentPane().add(jScrollPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 328, 160, 109));

        campoInterpretes.setMaximumSize(new java.awt.Dimension(420, 0));
        jScrollPane1.setViewportView(campoInterpretes);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(176, 328, 160, 109));

        btnRemoveAutor.setText("Remover autor");
        btnRemoveAutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveAutorActionPerformed(evt);
            }
        });
        getContentPane().add(btnRemoveAutor, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 443, -1, -1));

        btnRemoveInterprete.setText("Remover Interprete");
        btnRemoveInterprete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveInterpreteActionPerformed(evt);
            }
        });
        getContentPane().add(btnRemoveInterprete, new org.netbeans.lib.awtextra.AbsoluteConstraints(186, 443, -1, -1));

        jButton5.setText("Salvar");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(273, 486, -1, -1));

        jButton6.setText("Cancelar");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(192, 486, -1, -1));
        getContentPane().add(duracaoI, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 150, -1));
        getContentPane().add(anoI, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 230, 160, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAdicionarAutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarAutorActionPerformed
        // TODO add your handling code here:
        String autor = duracaoI.getText();
        if (autor != null && !autor.equals("")) {
            this.listaAutores.addElement(autor);
            campoAutores.setModel(listaAutores);
        } else {
            JOptionPane.showMessageDialog(null, "O nome do autor precisa ser informado.");
        }
    }//GEN-LAST:event_btnAdicionarAutorActionPerformed

    private void btnAdicionarInterpreteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarInterpreteActionPerformed
        // TODO add your handling code here:
        String interprete = campoInterprete.getText();
        if (interprete != null && !interprete.equals("")) {
            this.listaInterpretes.addElement(interprete);
            campoInterpretes.setModel(listaInterpretes);
        } else {
            JOptionPane.showMessageDialog(null, "O nome do interprete precisa ser informado.");
        }
    }//GEN-LAST:event_btnAdicionarInterpreteActionPerformed

    private void btnRemoveAutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveAutorActionPerformed
        // TODO add your handling code here:
        int autorSelecionado = campoAutores.getSelectedIndex();
        if (autorSelecionado != -1) {
            this.listaAutores.remove(autorSelecionado);
            campoAutores.setModel(listaAutores);
            JOptionPane.showMessageDialog(null, "Autor removido com sucesso! ");

        } else {
            JOptionPane.showMessageDialog(null, "Selecione o autor que você deseja remover na caixa de texto acima.");
        }
    }//GEN-LAST:event_btnRemoveAutorActionPerformed

    private void btnRemoveInterpreteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveInterpreteActionPerformed
        // TODO add your handling code here:
        int interpreteSelecionado = campoInterpretes.getSelectedIndex();
        if (interpreteSelecionado != -1) {
            this.listaInterpretes.remove(interpreteSelecionado);
            campoInterpretes.setModel(listaInterpretes);
            JOptionPane.showMessageDialog(null, "Interprete removido com sucesso! ");
        } else {
            JOptionPane.showMessageDialog(null, "Seleciona o interprete que você deseja remover na caixa de texto acima.");
        }
    }//GEN-LAST:event_btnRemoveInterpreteActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton6ActionPerformed

    public List<String> getAutores() {
        ListModel<String> ListaDeAutores = campoAutores.getModel();
        List<String> listaAutoresNova = new ArrayList();
        for (int i = 0; i < ListaDeAutores.getSize(); i++) {
            if (!ListaDeAutores.getElementAt(i).equals("")) {
                listaAutoresNova.add(ListaDeAutores.getElementAt(i));
            }
        }
        return listaAutoresNova;
    }

    /**
     *
     * @return
     */
    public List<String> getInterpretes() {
        ListModel<String> modeloListaDeAutores = campoAutores.getModel();
        List<String> listaAutoresNova = new ArrayList();
        for (int i = 0; i < modeloListaDeAutores.getSize(); i++) {
            if (!modeloListaDeAutores.getElementAt(i).equals("")) {
                listaAutoresNova.add(modeloListaDeAutores.getElementAt(i));
            }
        }
        return listaAutoresNova;
    }

    public String getCaminho() {
        return caminhoI.getText();
    }

    public String getTitulo() {
        return tituloI.getText();
    }

    public String getDescricao() {
        return descricaoI.getText();
    }

    public String getIdioma() {
        return idiomaI.getText();
    }

    public String getGenero() {
        return generoI.getText();
    }

    public int getDuracao() {
        return Integer.parseInt(duracaoI.getText());
    }

    public int getAno() {
        return Integer.parseInt(anoI.getText());
    }

    public void setTabela(DefaultTableModel tabela) {
        this.tabela = tabela;
    }

    public void setModoEditar(String caminho, String titulo) {
        Musica musica1 = (Musica) colecao.consultarMidia(caminho);
        Musica musica2 = (Musica) colecao.consultarMidia(titulo);

        if ((musica1 != null && musica2 != null) && (musica1.equals(musica2))) {
            this.musicaAnterior = musica1;
            this.caminhoI.setText(musica1.getCaminho());
            this.tituloI.setText(musica1.getTitulo());
            this.descricaoI.setText(musica1.getDescricao());
            this.idiomaI.setText(musica1.getIdioma());
            this.generoI.setText(musica1.getGenero());

            musica1.getAutores().forEach((autor) -> {
                listaAutores.addElement(autor);
            });
            campoAutores.setModel(listaAutores);
            musica1.getInterpretes().forEach((interprete) -> {
                listaInterpretes.addElement(interprete);
            });
            campoInterpretes.setModel(listaInterpretes);
            this.duracaoI.setValue(musica1.getDuracao());
            this.anoI.setValue(musica1.getAno());

        } else {
            JOptionPane.showMessageDialog(null, "Erro inesperado.");
        }
    }

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        try {
            Musica musica = new Musica(getCaminho(), getTitulo(), getDescricao(), getIdioma(), getGenero(), getAutores(), getInterpretes(), getDuracao(), getAno());
            colecao.cadastrarMidia(musica);
            JOptionPane.showMessageDialog(null, "Midia inserida com sucesso.");
            dispose();

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        } catch (IllegalArgumentException e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_jButton5ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFormattedTextField anoI;
    private javax.swing.JButton btnAdicionarAutor;
    private javax.swing.JButton btnAdicionarInterprete;
    private javax.swing.JButton btnRemoveAutor;
    private javax.swing.JButton btnRemoveInterprete;
    private javax.swing.JTextField caminhoI;
    private javax.swing.JTextField campoAutor;
    private javax.swing.JList<String> campoAutores;
    private javax.swing.JTextField campoInterprete;
    private javax.swing.JList<String> campoInterpretes;
    private javax.swing.JTextField descricaoI;
    private javax.swing.JFormattedTextField duracaoI;
    private javax.swing.JTextField generoI;
    private javax.swing.JTextField idiomaI;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField tituloI;
    // End of variables declaration//GEN-END:variables
}
