/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import colecao.ColecaoJogos;

import java.io.File;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.UnsupportedEncodingException;
import java.util.ArrayList;

import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.event.TableModelEvent;
import javax.swing.event.TableModelListener;
import javax.swing.filechooser.FileFilter;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;

import midia.Jogo;
import midia.Midia;

/**
 *
 * @author Gustavo Bittecourt Satheler
 * <gustavo.satheler@alunos.unipampa.edu.br>
 * <gustavosatheler@gmail.com>
 */
public class TelaOld extends javax.swing.JFrame {

    private ColecaoJogos colecaoJogos;
    DefaultTableModel tabelaJogos;

    /**
     * Creates new form Principal
     */
    public TelaOld() {
        initComponents();
        this.colecaoJogos = new ColecaoJogos(new ArrayList());
        this.tabelaJogos = (DefaultTableModel) jTable2.getModel();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane_colecoes = new javax.swing.JTabbedPane();
        jPanel_colecaoJogos = new javax.swing.JPanel();
        jButton_Jogos_importar = new javax.swing.JButton();
        jButton_Jogos_exportar = new javax.swing.JButton();
        jLabel_Jogos_titulo = new javax.swing.JLabel();
        jButton_Jogos_cadastrar = new javax.swing.JButton();
        jButton_Jogos_excluir = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Biblioteca de mídias");

        jTabbedPane_colecoes.setTabPlacement(javax.swing.JTabbedPane.LEFT);

        jButton_Jogos_importar.setText("Importar arquivo");
        jButton_Jogos_importar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Jogos_importarActionPerformed(evt);
            }
        });

        jButton_Jogos_exportar.setText("Exportar arquivo");
        jButton_Jogos_exportar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Jogos_exportarActionPerformed(evt);
            }
        });

        jLabel_Jogos_titulo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel_Jogos_titulo.setText("Biblioteca de Jogos");

        jButton_Jogos_cadastrar.setText("Cadastrar novo");

        jButton_Jogos_excluir.setText("Excluir selecionado");

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Teste", "Teste", "Teste", "Teste"},
                {"Teste1", "Teste1", "Teste1", "Teste1"},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable2);

        javax.swing.GroupLayout jPanel_colecaoJogosLayout = new javax.swing.GroupLayout(jPanel_colecaoJogos);
        jPanel_colecaoJogos.setLayout(jPanel_colecaoJogosLayout);
        jPanel_colecaoJogosLayout.setHorizontalGroup(
            jPanel_colecaoJogosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_colecaoJogosLayout.createSequentialGroup()
                .addGroup(jPanel_colecaoJogosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_colecaoJogosLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton_Jogos_excluir))
                    .addGroup(jPanel_colecaoJogosLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel_colecaoJogosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel_colecaoJogosLayout.createSequentialGroup()
                                .addComponent(jLabel_Jogos_titulo, javax.swing.GroupLayout.DEFAULT_SIZE, 295, Short.MAX_VALUE)
                                .addGap(514, 514, 514)
                                .addComponent(jButton_Jogos_cadastrar)
                                .addGap(39, 39, 39)
                                .addComponent(jButton_Jogos_importar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton_Jogos_exportar))
                            .addComponent(jScrollPane2))))
                .addContainerGap())
        );
        jPanel_colecaoJogosLayout.setVerticalGroup(
            jPanel_colecaoJogosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_colecaoJogosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_colecaoJogosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_colecaoJogosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel_Jogos_titulo)
                        .addComponent(jButton_Jogos_cadastrar))
                    .addGroup(jPanel_colecaoJogosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton_Jogos_importar)
                        .addComponent(jButton_Jogos_exportar)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 646, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton_Jogos_excluir)
                .addGap(3, 3, 3))
        );

        jTabbedPane_colecoes.addTab("Jogos", jPanel_colecaoJogos);
        jPanel_colecaoJogos.getAccessibleContext().setAccessibleName("Jogos");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane_colecoes)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane_colecoes)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_Jogos_exportarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Jogos_exportarActionPerformed
        String arquivo = carregarArquivo();

        try {
            colecaoJogos.exportarMidias(arquivo);
            JOptionPane.showMessageDialog(null, "Mídias exportadas com sucesso.");
        } catch (FileNotFoundException ex) {
            Logger.getLogger(TelaOld.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "Arquivo não encontrado.");
        } catch (UnsupportedEncodingException ex) {
            Logger.getLogger(TelaOld.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "Arquivo com codificação não suportada.");
        } catch (NullPointerException | ClassCastException ex) {
            Logger.getLogger(TelaOld.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, ex.getMessage());
        } catch (IOException ex) {
            Logger.getLogger(TelaOld.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "Não foi possivel exportar.");
        }
    }//GEN-LAST:event_jButton_Jogos_exportarActionPerformed

    private void jButton_Jogos_importarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Jogos_importarActionPerformed
        String arquivo = carregarArquivo();

        try {
            colecaoJogos.importarMidias(arquivo);
            JOptionPane.showMessageDialog(null, "Mídias inseridas com sucesso.");

        } catch (NumberFormatException ex) {
            Logger.getLogger(TelaOld.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "Dados incompatíveis com essa mídia.");

        } catch (NullPointerException ex) {
            Logger.getLogger(TelaOld.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "Nenhum arquivo foi selecionado.");

        } catch (IOException ex) {
            Logger.getLogger(TelaOld.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "Não foi possivel inserir a mídia.\n" + ex.getMessage());
        }

        tabelaJogos.setRowCount(0);

        for (Object midia : colecaoJogos.exibirMidia()) {
            Jogo jogo = (Jogo) midia;
            tabelaJogos.addRow(new Object[]{
                jogo.getCaminho(),
                jogo.getTitulo(),
                jogo.getDescricao(),
                jogo.getGenero(),
                jogo.getAutores(),
                jogo.getAno(),
                jogo.getNumeroJogadores(),
                jogo.hasSuporteRede()
            });
        }
    }//GEN-LAST:event_jButton_Jogos_importarActionPerformed

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked

        //JOptionPane.showMessageDialog(null, );
        

    }//GEN-LAST:event_jTable2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaOld.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaOld.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaOld.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaOld.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaOld().setVisible(true);
            }
        });
    }

    public static String carregarArquivo() {

        File arquivo;

        JFileChooser chooser = new JFileChooser();

        FileFilter filter = new FileNameExtensionFilter("Arquivo de texto", "txt");
        chooser.addChoosableFileFilter(filter);
        chooser.setAcceptAllFileFilterUsed(false);

        int retorno = chooser.showOpenDialog(null);

        if (retorno == JFileChooser.APPROVE_OPTION) {
            arquivo = chooser.getSelectedFile();
            return arquivo.getPath();
        }

        return null;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Jogos_cadastrar;
    private javax.swing.JButton jButton_Jogos_excluir;
    private javax.swing.JButton jButton_Jogos_exportar;
    private javax.swing.JButton jButton_Jogos_importar;
    private javax.swing.JLabel jLabel_Jogos_titulo;
    private javax.swing.JPanel jPanel_colecaoJogos;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane_colecoes;
    private javax.swing.JTable jTable2;
    // End of variables declaration//GEN-END:variables
}
